# (c) 2025 Jonathan Brandt
# Licensed under the MIT License. See LICENSE file in the project root.

import re
import string
import os
from io import BytesIO
import glob
import json

from pathlib import Path
from copy import copy
from datetime import datetime
from html import unescape

from openpyxl import load_workbook
from openpyxl.worksheet.formula import ArrayFormula
from openpyxl.formula.translate import Translator
from openpyxl.utils.cell import get_column_letter

from birddog.utility import get_text, is_linked, link_status
from birddog.wiki import ARCHIVE_BASE
from birddog.ai import classify_table_columns
from birddog.task import TaskManager
from birddog.cache import load_cached_object, save_cached_object, remove_cached_object, CacheMissError
from birddog.store import get_key_value_store

from birddog.logging import get_logger
_logger = get_logger()

# ------------ HELPER FUNCTIONS ---------------

def _format_date(date_str):
    """
    Converts a date string from 'YYYY,MM,DD,hh:mm' to 'DD Mon YYYY'.
    
    Example:
        format_date('2024,04,14,07:30') -> '14 Apr 2024'
    """
    if not date_str:
        return ''
    dt = datetime.strptime(date_str, "%Y,%m,%d,%H:%M")
    return dt.strftime("%d %b %Y")

def _child_url(child):
    link = child[0]["link"]
    return ARCHIVE_BASE + link if link is not None else None

def _child_sheetname(page, child):
    if page.kind == 'archive':
        return f'Fund {unescape(get_text(child[0]["text"]))}'
    elif page.kind == 'fond':
        return f'{page.parent.id} {page.id}-{unescape(get_text(child[0]["text"]))}'
    return f'sheetname-{unescape(get_text(child[0]["text"]))}'

def _child_doc_url(child):
    if len(child) < 2:
        return None
    link = child[1]["link"]
    return ARCHIVE_BASE + link if link is not None else None

_EXPR_PATTERN = re.compile(r'{[^}]+}')

def _check_string(text):
    if not text:
        return None
    if not isinstance(text, str):
        return text
    match = re.findall(_EXPR_PATTERN, text)
    if not match:
        return None
    return list(match)

def _get_cell_text(cell):
    text = cell.value
    if isinstance(text, ArrayFormula):
        text = text.text
    return text

def _check_cell(cell):
    #_logger.info(f'_check_cell[{cell.coordinate}]: {cell.value}')
    return _check_string(_get_cell_text(cell))

def _is_integer(text):
    return text is not None and text.isdigit()

_PARSE_PATTERN = re.compile(
    r'{(?P<expr>[a-zA-Z0-9_.]+)(\[(?P<index>[a-zA-Z_][a-zA-Z0-9_]*|\d+)\])?(\:(?P<modifier>[a-zA-Z_]+))?}')

def _parse_template_expr(expr):
    match = re.match(_PARSE_PATTERN, expr)
    return match.groupdict() if match else None

def _substitute(page, expr):
    try:
        fstring = '{__page__.' + expr['expr'] + '}'
        result = string.Formatter().format(fstring, __page__=page)
        if result == "None":
            result = ""
        return result
    except:
        return ""

def _copy_cell_properties(source, dest):
    # propagate border, style, font, fill, and alignment to all rows
    dest.style = source.style
    dest.border = copy(source.border)
    dest.alignment = copy(source.alignment)
    dest.font = copy(source.font)
    dest.fill = copy(source.fill)

def _process_formula(sheet, cell, first_child_row, last_child_row):
    if cell.row > first_child_row and cell.row <= last_child_row:
        # ignore table rows that are generated by progenitor table row (already handled)
        return
    text = _get_cell_text(cell)
    if isinstance(text, str) and (text[0] == '=' or text.startswith("__EQ__")):
        # formula detected
        column_range = f'{cell.column_letter}{first_child_row}:{cell.column_letter}{last_child_row}'
        if text[0] == "=":
            text = text[1:]
        elif text.startswith("__EQ__"):
            text = text[6:]
        text = text.replace("__COL__", column_range)
        text = text.replace("__FIRST__", str(first_child_row))
        text = text.replace("__LAST__", str(last_child_row))
        new_formula = f'={text}'
        #_logger.info(f'formula found: {cell.column_letter}{cell.row}: {text[1:]} --> {new_formula}')
        cell.value = new_formula
        if cell.row == first_child_row:
            # handle formula inside table
            for row in range((first_child_row+1), (last_child_row+1)):
                child_cell = sheet.cell(row=row, column=cell.column)
                _copy_cell_properties(cell, child_cell)
                child_cell.value = Translator(
                    new_formula, origin=cell.coordinate).translate_formula(child_cell.coordinate)

def _map_index(column_header_map, index):
    if index is None:
        return None

    # Convert stringified integers
    if isinstance(index, int) or _is_integer(index):
        return [int(index)]

    # Look up by name
    result = column_header_map.get(index)
    if isinstance(result, int):
        return [result]
    if isinstance(result, list):
        return result

    return None


def _set_url(cell, link_flag, url, edit_cell):
    if link_flag == "exists":
        cell.hyperlink = url
        cell.font = copy(edit_cell['linked'].font)
    elif link_flag == "linked":
        cell.hyperlink = url + "?action=edit&redlink=1"
        cell.font = copy(edit_cell['nonexistent'].font)
    else: # "unlinked" status
        cell.font = copy(edit_cell['unlinked'].font)

def _update_edit_state(entry, edit_state):
    edit_update = entry.get('edit')
    if edit_update == 'added':
        return edit_update
    if edit_update == 'changed' and edit_state != 'added':
        return edit_update
    return edit_state

def _update_link_status(entry, prev_link_status):
    cur_link_status = link_status(entry)
    if cur_link_status == 'exists':
        return cur_link_status
    if cur_link_status == 'linked' and prev_link_status != 'exists':
        return cur_link_status
    return prev_link_status

def _process_table_column(table, column_header_map, edit_cell, sheet, cell, parse, match):
    row = cell.row
    col = cell.column
    index = parse['index']
    #_logger.info(f"filling table column: {col}({index}), expr={parse['expr']}")
    mapped_index_list = _map_index(column_header_map, index)
    if index is not None or mapped_index_list is not None:
        _logger.info(f'column map: {index} -> {mapped_index_list}')
    cell_text = _get_cell_text(cell)
    for child in table["children"]:
        child_cell = sheet.cell(row=row, column=col)
        if child_cell.row != cell.row:
            # propagate border, style, font, and alignment to all rows
            _copy_cell_properties(cell, child_cell)
        if parse['expr'] == 'child':
            if mapped_index_list is not None:
                cell_value = []
                cell_hyperlink = None
                cell_edit_status = None
                for mapped_index in mapped_index_list:
                    if mapped_index < len(child):
                        table_entry = child[mapped_index]
                        cell_value.append(unescape(get_text(table_entry['text'])))
                        cell_edit_status = _update_edit_state(table_entry, cell_edit_status)
                        #_logger.info(f"cell value: {table_entry}, edit status: {cell_edit_status}")
                if cell_edit_status in edit_cell:
                    child_cell.fill = copy(edit_cell[cell_edit_status].fill)
                if parse['modifier'] == 'linked':
                    child_link_status = link_status(child[0])
                    _set_url(child_cell, child_link_status, _child_url(child), edit_cell)
                elif parse['modifier'] == 'doc_link':
                    doc_link_status = link_status(child[1]) if len(child) > 1 else "unlinked"
                    #_logger.info(f"col B: {get_text(child[0]['text'])}, {doc_link_status}, {_child_doc_url(child)}")
                    _set_url(child_cell, doc_link_status, _child_doc_url(child), edit_cell)
                child_cell.value = "; ".join(cell_value)
        elif parse['expr'] == 'empty':
            child_cell.value = ''
        elif parse['expr'] == 'col':
            contents = cell_text.replace("{col}", "")
            #_logger.info(f"col cell: {contents}")
            if row == cell.row or contents[0] != "=":
                child_cell.value = contents
            else:
                child_cell.value = Translator(
                    contents, origin=cell.coordinate).translate_formula(child_cell.coordinate)
        row += 1
    #_logger.info(f"finished table column: {col}({index})")

def _locate_first_child_row(sheet):
    for row in sheet.iter_rows():
        for cell in row:
            check = _check_cell(cell)
            if check:
                # form list of parsed template expressions for each in the cell
                parsed = [_parse_template_expr(e) for e in check]
                for parse in parsed:
                    # look for child cell expression
                    if parse['expr'] in ['empty', 'child']:
                        return cell.row
    return None

def _process_title(page, sheet):
    title = sheet.title
    check = _check_string(title)
    if check:
        for expr in check:
            parsed = _parse_template_expr(expr)
            sub = _substitute(page, parsed)
            if sub:
                title = title.replace(expr, sub)
    sheet.title = title

# ------------ EXPORT PAGE ---------------

_PROJECT_ROOT = Path(__file__).resolve().parents[1]
_TEMPLATE_DIR = _PROJECT_ROOT / 'resources' / 'xlsx_templates'

def list_templates():
    pattern = os.path.join(_TEMPLATE_DIR, '*.xlsx')
    return [os.path.basename(f) for f in glob.glob(pattern)]

def export_page(page, dest_file=None, template=None, table_name=None, column_map=None):
    # load template file that matches this kind of page
    _logger.info(f"export_page({page.title}: template='{template}', table_name='{table_name}', column_map='{column_map}')")
    if not template:
        template_file = f'{_TEMPLATE_DIR}/{page.kind}.xlsx'
    else:
        template_file = f'{_TEMPLATE_DIR}/{template}'
    _logger.info(f'opening template file {template_file}...')
    workbook = load_workbook(filename = template_file)
    sheet = workbook.active
    max_row = sheet.max_row
    max_col = sheet.max_column
    max_col_letter = get_column_letter(max_col)
    _logger.info(f'sheet dimensions: {max_row} rows, {max_col} cols')

    _process_title(page, sheet)

    # determine selected table for export
    if not table_name:
        table_name = page.tables[0]["name"] if page.tables else ""
    table = page.lookup_table(table_name)
    # construct column header map if needed
    column_header_map = column_map if column_map else classify_table_columns(table)

    # move rows below the table downward to make room for table rows
    num_children = len(table["children"])
    first_child_row = _locate_first_child_row(sheet)
    last_child_row = first_child_row + max(num_children, 1) - 1
    _logger.info(f"export_page: first_child_row={first_child_row}, last_child_row={last_child_row}")
    footer_range = f'A{first_child_row+1}:{max_col_letter}{max_row}'
    _logger.info(f'moving cell range: {footer_range}')
    sheet.move_range(footer_range, rows=num_children-1, cols=0, translate=False)

    # make a list of all cells with template expressions
    # (now that cells have been relocated to their final positions)
    edit_cell = {} # saves cells containing edit and formatting prototypes
    edits = [] # list of edits to be processed
    for row in sheet.iter_rows():
        for cell in row:
            check = _check_cell(cell)
            if check:
                # form list of parsed template expressions for each in the cell
                parsed = [_parse_template_expr(e) for e in check]
                for parse in parsed:
                    # check for formatting directives (before actually editing)
                    if parse['expr'] == 'edit':
                        # {edit} cells contain formatting for editing highlights
                        # save these for later use in a dict keyed on the edit modifier
                        edit_cell[parse['modifier']] = cell
                    else:
                        edits.append((cell, check, parsed))
            else:
                # check for and handle a formula
                _process_formula(sheet, cell, first_child_row, last_child_row)

    # process all the edit expressions
    for edit in edits:
        cell, matches, parses = edit
        for match, parse in zip(matches, parses):
            #_logger.info(f"processing template match: {match}, {parse}")
            if parse['expr'] in ['empty', 'child', 'col']:
                _process_table_column(
                    table, 
                    column_header_map, 
                    edit_cell, 
                    sheet, 
                    cell, 
                    parse, 
                    match)
            elif parse['expr'] == 'edit':
                # {edit} cells contain formatting for editing highlights (caught above)
                pass
            else:
                # general case: replace template expression with substitution value
                _logger.info(f"export_page template: {cell.coordinate} == {cell.value}")
                sub = _substitute(page, parse)
                if sub is not None:
                    sub = unescape(sub)
                    cell.value = cell.value.replace(match, sub)
                if parse['modifier'] == 'linked':
                    cell.hyperlink = page.url
                    cell.font = copy(edit_cell['linked'].font)
                if parse['modifier'] == 'doc_link':
                    doc_url = page.doc_url
                    if doc_url:
                        cell.hyperlink = doc_url
                        cell.font = copy(edit_cell['linked'].font)
                    if 'doc_link_edit' in page.page:
                        edit = page.page['doc_link_edit']
                        if edit in edit_cell:
                            cell.fill = copy(edit_cell[edit].fill)
                if parse['modifier'] == 'date':
                    cell.value = _format_date(cell.value)

    # all done, save and return
    if dest_file:
        _logger.info("writing export sheet to file")
        workbook.save(dest_file)
    _logger.info("finished table export")
    return workbook

class ExportManager(TaskManager):
    def __init__(self, runtime):
        self._runtime = runtime
        super().__init__("ExportManager")

    def _output_path(self, task_id):
        return f"export/{task_id}.xlsx"

    def export_page(self, title, compare=None, table_name=None, template=None, column_map=None):
        subtask = { 
            "title": title,
            "compare": compare,
            "table_name": table_name,
            "template": template,
            "column_map": column_map,
        }
        # return task_id to caller for subsequent lookup
        return self.create(title, [ subtask ])

    def is_complete(self, task_id):
        try:
            if load_cached_object(self._output_path(task_id)):
                return True
            return False
        except CacheMissError:
            return False
        except Exception as e:
            raise e

    def get_result(self, task_id):
        try:
            output = load_cached_object(self._output_path(task_id))
            if output:
                output_buffer = BytesIO()
                _logger.info(f"output size: {len(output)}")
                output_buffer.write(bytes.fromhex(output))
                output_buffer.seek(0)
                remove_cached_object(self._output_path(task_id))
                return output_buffer
            return None
        except CacheMissError:
            return None
        except Exception as e:
            raise e

    def execute_subtask(self, subtask):
        payload = subtask["payload"]
        try:
            page = self._runtime.lookup_by_title(payload["title"])
            if page:
                # avoid persisting any subsequent changes
                page = page.detached_copy()

                # put page into desired state for export
                page.prepare_to_download()
                ref_date = payload.get("compare")
                if ref_date:
                    page = page.compare(ref_date)

                # export into output memory buffer
                output_buffer = BytesIO()
                export_page(
                    page, 
                    output_buffer, 
                    payload.get("template"), 
                    payload.get("table_name"),
                    payload.get("column_map"))

                # serialize output to temp storage
                output_buffer.seek(0)
                save_cached_object(output_buffer.read().hex(), self._output_path(subtask['task_id']))

                output_buffer.seek(0)
                _logger.info(f"{subtask['task_id']}: export task finished. output length: {len(output_buffer.read())}")
        except Exception as err:
            _logger.info(f"Exception in export task: {err}")

    def complete_task(self, task_desc, subtasks):
        _logger.info(f"{task_desc['task_id']}: completed")

