# (c) 2025 Jonathan Brandt
# Licensed under the MIT License. See LICENSE file in the project root.

"""
Wiki API access functions
"""

import time
import json
import requests
import re
from datetime import datetime
from urllib.parse import quote, unquote

import mwparserfromhell
from itertools import islice
from cachetools import LRUCache
from bs4 import BeautifulSoup

from birddog.utility import (
    from_utc_format,
    to_utc_format,
    equal_text,
    fetch_url,
    form_text_item,
    format_date,
    get_text,
    lastmod,
    match_text,
    translate_page,
    is_linked,
    )

from birddog.logging import get_logger
_logger = get_logger()

# INITIALIZATION --------------------------------------------------------------

# global constants

ARCHIVE_BASE    = 'https://uk.wikisource.org'
WIKI_NAMESPACE  = 'Архів'
WIKI_NAMESPACE_ID = '116'
ARCHIVES        = None
API_URL         = f"{ARCHIVE_BASE}/w/api.php"

# load static data resources

_archive_master_path = 'resources/archives_master.json'

with open(_archive_master_path, encoding="utf8") as f:
    data = json.load(f)
    ARCHIVES = data['archives']

def _inventory_subarchives(archives):
    subarchives = {}
    for arc in archives.values():
        for sub in arc.values():
            subarchives[sub['subarchive']['uk']] = sub['subarchive']
    return list(subarchives.values())

SUBARCHIVES = _inventory_subarchives(ARCHIVES)

# -------------------------------------------------------------------------------
# namespace id lookup (utility)

def lookup_namespace_id(name):
    params = {
        "action": "query",
        "format": "json",
        "meta": "siteinfo",
        "siprop": "namespaces|namespacealiases"
    }
    data = fetch_url(API_URL, params=params, json=True)
    data = data["query"]
    #_logger.info(data)
    target = name.lower()
    # Check official namespaces
    for ns_id, ns in data["namespaces"].items():
        if ns.get("canonical","").lower() == target or ns.get("*","").lower() == target:
            return int(ns_id)
    # Check aliases
    for alias in data.get("namespacealiases", []):
        if alias["alias"].lower() == target:
            return int(alias["id"])
    return None

# -------------------------------------------------------------------------------
# return list of all pages in given namespace with given prefix (or all if prefix is None)

def get_all_pages(namespace=WIKI_NAMESPACE_ID, prefix=None, limit=500):
    titles = []
    params = {
        "action": "query",
        "format": "json",
        "list": "allpages",
        "apnamespace": namespace,
        "aplimit": limit,
    }
    if prefix:
        params["apprefix"] = prefix.replace(f"{WIKI_NAMESPACE}:", "")

    cont = {}
    while True:
        if cont:
            params.update(cont)
        data = fetch_url(API_URL, params=params, json=True)
        titles.extend([p["title"] for p in data["query"]["allpages"]])
        if "continue" in data:
            cont = data["continue"]
            #time.sleep(5)
        else:
            break
    return titles

# -------------------------------------------------------------------------------
# subarchive sniffer

def sniff_subarchives(archive):
    url = f'{ARCHIVE_BASE}/wiki/{archive}'
    result = {}
    soup = BeautifulSoup(requests.get(url).text, 'lxml')
    for div in soup.find_all('div', attrs = {'id': 'mw-content-text'}):
        for item in div.find_all('a'):
            if item.has_attr('title'):
                if item['title'].startswith(archive) or item['title'].replace(" ", "_").startswith(archive):
                    if 'redlink' not in item['href']:
                        parsed = item['title'].split('/')
                        if len(parsed) == 2 and parsed[1] != 'видання':
                            subarchive = parsed[1]
                            _logger.info(f'found subarchive: {parsed[0]}-{parsed[1]}')
                            result[subarchive] = {
                                'title': form_text_item(item['title']),
                                'archive': form_text_item(parsed[0]),
                                'subarchive': form_text_item(parsed[1]),
                                'description': form_text_item(item.text),
                                'link': item['href'],
                                }
    return result

def _comment_string():
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"This file was generated by update_master_archive_list() on {timestamp}. Do not edit manually."

def update_master_archive_list():
    with open('resources/archives.json', encoding="utf8") as f:
        manifest = json.load(f)
    
    archives = {}
    for archive_name, archive in manifest["archives"].items():
        _logger.info(f"Searching {archive_name}")
        archives[archive_name] = sniff_subarchives(archive)
        translate_page(archives[archive_name])
        for sub, value in archives[archive_name].items():
            if sub == "Р":  # make sure Cyrillic Р maps to Latin R
                _logger.info("Mapping Cyrillic Р to Latin R")
                value["subarchive"]["en"] = "R"
            elif sub == "А": # make sure Cyrillic А maps to Latin A
                _logger.info("Mapping Cyrillic А to Latin A")
                value["subarchive"]["en"] = "A"

    for fond_name, fond_title in manifest["fonds"].items():
        fond_name = fond_name.split('-')
        if len(fond_name) == 1:
            fond_name.append('_')
        item = {
            "title": form_text_item(fond_title),
            "subarchive": form_text_item(fond_name[1])
        }
        translate_page(item)
        if not archives.get(fond_name[0]):
            archives[fond_name[0]] = {}
        archives[fond_name[0]][fond_name[1]] = item

    _logger.info(f"generate_master_archive_list: updating {_archive_master_path}")
    with open(_archive_master_path, "w") as file:
        file.write(json.dumps({ 
            'comment':  _comment_string(),
            'archives': archives
            }, indent=4))

def all_archives():
    return [[arc, sub['subarchive']['en']] for arc, archive in ARCHIVES.items() for sub in archive.values()]

def _select_subarchive(archive, subarchive):
    for key, value in archive.items():
        if subarchive is None or key == subarchive or value["subarchive"]["en"] == subarchive:
            return value

def find_archive(archive_tag, subarchive=None):
    archive = ARCHIVES[archive_tag]
    sub = _select_subarchive(archive, subarchive)
    return { "title": sub["title"], "subarchive": sub["subarchive"] }

# -------------------------------------------------------------------------------
# WikiSource MediaWiki API page download

def get_title(url):
    result = url.replace(ARCHIVE_BASE, '')
    result = result.replace('/wiki/', '')
    result = unquote(result)
    if not result.startswith(f"{WIKI_NAMESPACE}:"):
        result = f"{WIKI_NAMESPACE}:{result}"
    return result

def _is_table(tag):
    return tag.tag == "table" and [entry for entry in tag.attributes if "wikitable" in entry] != []
 
def _check_page_existence_chunked(page_links, chunk_size=50):
    exists_map = {}
    title_map = {get_title(link): link for link in page_links}
    titles = list(title_map.keys())
    title_map = {key.replace(" ", "_").lower(): link for key, link in title_map.items()}
    #for key, value in title_map.items():
    #    print(key, value)
    #print("check_page_existence_chunked:", titles)
    
    for i in range(0, len(titles), chunk_size):
        title_batch = "|".join(titles[i:i+chunk_size])
        #print("batch:", i, "title length:", len(title_batch))
        params = {
            'action': 'query',
            'prop': 'info',
            'titles': title_batch,
            'format': 'json'
        }
        data = fetch_url(API_URL, params=params, json=True, method="POST")
        for page_id, page_data in data['query']['pages'].items():
            title = page_data['title'].replace(" ", "_").lower()
            #if title == "архів:дажо/1/74/":
            #    print('\n', title, page_data, params)
            # If invalid or missing, mark as False
            exists = not ('missing' in page_data or 'invalid' in page_data)
            exists_map[title_map[title]] = exists
    return exists_map

def _is_category_link(title):
    return title.startswith("Категорія:")
    
def _is_commons_url(title):
    return title.lower().startswith("c:")
    
def _map_commons_url(title):
    if title.lower().startswith("c:"):
        return f"https://commons.wikimedia.org/wiki/{title[2:].replace(' ', '_')}"
    return title

def _is_relative_link_target(link_target):
    return re.match(r'^(\.\./|\.\/|/)', link_target) is not None

def _is_familysearch_url(link):
    return link.startswith("https://www.familysearch.org")

def _expand_link_target(link_target, page_title):
    link_target = link_target.strip().replace(" ", "_")
    link_target = re.sub(r'//+', '/', link_target)

    # Split the page_title into components
    base_parts = page_title.strip("/").split("/")
    target_parts = link_target.strip("/").split("/")

    resolved_parts = []
    for part in target_parts:
        if part == "..":
            if base_parts:
                base_parts.pop()
        elif part == "." or part == "":
            continue
        else:
            resolved_parts.append(part)

    final_parts = base_parts + resolved_parts
    full_path = "/".join(final_parts).replace(" ", "_")

    return f"{ARCHIVE_BASE}/wiki/{full_path}"

def _split_list(lst, *predicates):
    buckets = [[] for _ in range(len(predicates) + 1)]  # One extra for "rest"
    for item in lst:
        for i, pred in enumerate(predicates):
            if pred(item):
                buckets[i].append(item)
                break
        else:
            buckets[-1].append(item)  # No predicate matched
    return tuple(buckets)

def _safe_remove(lst, item):
    try:
        lst.remove(item)
    except ValueError:
        pass

def _subtract_links(links, delta):
    for key, link_list in delta.items():
        if key in links.keys():
            for delta_link in link_list:
                _safe_remove(links[key], delta_link)

def _extract_links(wikitext):
    # parse if necessary
    if not isinstance(wikitext, mwparserfromhell.wikicode.Wikicode):
        wikitext = mwparserfromhell.parse(str(wikitext))

    # Internal wiki link targets
    links = [str(link.title).strip() for link in wikitext.filter_wikilinks()]    
    commons_links, category_links, int_links = _split_list(links, _is_commons_url, _is_category_link)
    commons_links = [_map_commons_url(title) for title in commons_links]
    
    # External link URLs
    ext_links = [str(link.url).strip() for link in wikitext.filter_external_links()]

    return { 
        "commons_links": commons_links,
        "category_links": category_links,
        "internal_links": int_links,
        "external_links": ext_links,
    }

def _read_wiki_text(page_title, oldid=None):
    params = {
        'action': 'parse',
        'prop': 'wikitext|revid',
        'format': 'json'
    }
    if oldid:
        params['oldid'] = oldid
    elif page_title:
        params['page'] = page_title
    else:
        raise ValueError("Must provide either page_title or oldid")
        
    data = fetch_url(API_URL, params=params, json=True)

    if 'error' in data:
        raise RuntimeError(f"API error: {data['error']}")
    
    return (
        data['parse']['wikitext']['*'], 
        data['parse']['revid'], 
        data['parse']['title'].replace(f'{WIKI_NAMESPACE}:', ''),
    )

def _extract_colspan(text):
    """Extracts colspan=N from text, returns N as int or 0 if absent."""
    match = re.search(r'\bcolspan\s*=\s*(\d+)', text, flags=re.IGNORECASE)
    return int(match.group(1)) if match else 0

def _expand_row_cells(cells):
    """
    Given a list of cell strings, expand any cell with colspan=N into N cells.
    Fills extra cells with empty strings.
    """
    expanded = []
    for cell in cells:
        colspan = _extract_colspan(cell)
        # Remove the colspan directive from the text
        clean_cell = re.sub(r'\bcolspan\s*=\s*\d+', '', cell, flags=re.IGNORECASE).strip(' |')
        if colspan > 1:
            expanded.append(clean_cell)
            expanded.extend([""] * (colspan - 1))
        else:
            expanded.append(clean_cell)
    return expanded

def _strip_attributes(cell_text):
    """
    Removes leading attributes from a Wikitext table cell, stopping at the first
    unescaped pipe that is not followed by another attribute.

    Attributes are considered anything before content and typically look like:
        'style="..."|align="..."|Some content'

    Escaped pipes (\\|) are preserved.

    :param cell_text: Wikitext for a single cell
    :return: Cleaned cell content string
    """

    # Split only on unescaped pipes
    parts = re.split(r'(?<!\\)\|', cell_text)

    # Strip whitespace and preserve escaped pipes
    parts = [part.strip().replace(r'\|', '|') for part in parts]

    # Heuristic: if more than one part, assume all but the last are attributes
    return parts[-1] if len(parts) > 1 else parts[0]

def _parse_wikitext_table_lines(wikitext):
    """
    Parse stripped Wikitext table content line-by-line.

    :param wikitext: A string containing the contents of a table, minus the outer {| and |}
    :return: List of rows, each row is a list of cells
    """
    rows = []
    current_row = []
    is_header = False

    lines = wikitext.strip().splitlines()

    for line in lines:
        line = line.strip()
        if not line:
            continue

        if line.startswith('|-'):
            if current_row:
                rows.append(current_row)
                current_row = []
            is_header = False  # reset after row break
            continue

        if line.startswith('|+'):
            continue  # ignore caption lines

        if line.startswith('!'):
            if not is_header and current_row:
                rows.append(current_row)
                current_row = []
            is_header = True
            line_content = line[1:]

            # Use both !! and || as possible header separators
            cells = re.split(r'\s*(?:!!|\|\|)\s*', line_content)
            current_row.extend(cells)
            continue

        if line.startswith('|'):
            if is_header:
                # terminate header
                rows.append(current_row)
                current_row = []
                is_header = False
            line_content = line[1:]
            cells = re.split(r'\s*\|\|\s*', line_content)
            current_row.extend(cells)
            continue

    if current_row:
        rows.append(current_row)

    # Apply attribute stripping and colspan expansion
    rows = [[_strip_attributes(cell) for cell in _expand_row_cells(row)] for row in rows]
    return rows

def _parse_wikitext_table(text):

    #with open("table_code.txt", "w") as file:
    #    file.write(str(text))

    # Split rows using the row separator "|-", allowing optional leading/trailing whitespace
    rows = re.split(r"\s*\|[-—]\s*", str(text))
    rows = [row.strip("\n ") for row in rows]
    rows = [row for row in rows if row] # get rid of empty rows
    
    #_logger.info(rows)

    header = []
    body = []

    body = _parse_wikitext_table_lines(text)
    if body:
        # take the first row as the header
        header = body.pop(0)

    # process colspan directives
    #header = _expand_row_cells(header)
    #body = [_expand_row_cells(row) for row in body]

    return header, body

def _included_link(link):
    return not any([
        _is_relative_link_target(link),
        _is_familysearch_url(link),
        re.search(r".(png|jpg)$", link, re.IGNORECASE),
        ])

def mw_page_doc_url(page):
    links = page["other_links"].get("internal_links", [])
    links = [link for link in links if _included_link(link)]
    if links:
        return _expand_link_target(links[0], page["title"]["uk"])
    links = page["notes"].get("commons_links", [])
    links = [link for link in links if _included_link(link)]
    if links:
        return links[0]
    links = page["other_links"].get("external_links", [])
    links = [link for link in links if _included_link(link)]
    if links:
        return links[0]
    return None

def mw_read_page(page_title, oldid=None):
    # extract title from url if necessary
    page_title = get_title(page_title)
    #_logger.info(f"mw_read_page: {page_title}")

    # get the wikitext and parse
    wikitext, revid, title = _read_wiki_text(page_title, oldid)
    wikicode = mwparserfromhell.parse(wikitext)

    # get and organize all the links on the page
    page_links = _extract_links(wikicode)

    # Title and description
    desc = None
    dates = None
    notes = {}
    template_name = None
    for template in wikicode.filter_templates():
        if template.name.startswith("Архіви") or template.name.startswith("заголовок"):
            template_name = template.name.strip(' \n')
            if template.has("назва"):
                desc = template.get("назва").value.strip_code().strip(" ./\n")
            if template.has("секція") and not desc:
                desc = template.get("секція").value.strip_code().strip()
            if template.has("рік"):
                dates = template.get("рік").value.strip_code().strip()
            if template.has("примітки"):
                notes = _extract_links(template.get("примітки"))
                # take the links found in the header section out of the master list
                # since they are now accounted for
                _subtract_links(page_links, notes)
            break

    page = {
        "title": form_text_item(title),
        "template": form_text_item(template_name),
        "revid": revid,
        "description": form_text_item(desc),
        "dates": form_text_item(dates),
        "notes": notes,
        "other_links": page_links
    }

    # Table data
    tables = [t for t in wikicode.filter_tags() if _is_table(t)]
    header = []
    children = []
    all_page_links = set()

    if tables:
        table_code = tables[0].contents # assume first table
        header, rows = _parse_wikitext_table(table_code)

        # format header
        header = [form_text_item(cell.strip()) for cell in header]

        # process rows
        for cells in rows:
            row_data = []
            for cell_text in cells:
                cell_wikicode = mwparserfromhell.parse(cell_text)
                # Extract internal links
                links = cell_wikicode.filter_wikilinks()
                link = None
                if links:
                    #print(links)
                    link_target = str(links[0].title).strip()
                    _safe_remove(page_links["internal_links"], link_target)
                    if not link_target.startswith("#"):
                        link = _expand_link_target(link_target, page_title)
                        #print("link target expanded:", link_target, link)
                        all_page_links.add(link)
                else:
                    # External links as fallback
                    ext_links = cell_wikicode.filter_external_links()
                    if ext_links:
                        link = str(ext_links[0].url).strip()
        
                # Clean text (strip wikitext markup)
                text = cell_wikicode.strip_code().strip('./ ')
                row_data.append({'text': form_text_item(text), 'link': link})
            children.append(row_data)

    if not header and not children:
        # try to populate a "table" if there is either a list of subpages or commons links
        sub_pages = [link for link in page_links["internal_links"] if link.startswith("/")]
        if sub_pages:
            # synthesize a table from list of links to subpages
            header = [ form_text_item("-") ]
            for link_target in sub_pages:
                link = _expand_link_target(link_target, page_title)
                all_page_links.add(link)
                _safe_remove(page_links["internal_links"], link_target)
                text = form_text_item(link_target.strip("./ "))
                children.append([{'text': text, 'link': link}])
        else:
            sub_pages = [link for link in page_links["commons_links"]]
            if len(sub_pages) > 1:
                # synthesize a table from list of links commons files
                header = [ form_text_item("-") ]
                for link in sub_pages:
                    _safe_remove(page_links["commons_links"], link)
                    text = link.replace("https://commons.wikimedia.org/wiki/", "")
                    text = text.replace("File:", "")
                    text = text.replace("_", " ")
                    text = form_text_item(text)
                    children.append([{'text': text, 'link': link, 'exists': True}])

    # Collect unique linked page titles (relative titles like '/1/' etc.)
    link_existence = _check_page_existence_chunked(all_page_links)
    #link_existence = {}
    for row in children:
        for cell in row:
            if cell['link']:
                cell['exists'] = link_existence.get(cell["link"], True)  # True by default
                # ARCHIVE_BASE is implicit for child links that are within the media wiki 
                cell["link"] = cell["link"].replace(ARCHIVE_BASE, "")

    page["header"] = header
    page["children"] = children

    # Last modified date via API `revisions` (for this oldid)
    params_rev = {
        'action': 'query',
        'prop': 'revisions',
        'revids': revid,
        'rvprop': 'timestamp',
        'format': 'json'
    }
    rev_data = fetch_url(API_URL, params=params_rev, json=True)

    pages = rev_data['query']['pages']
    page_id = next(iter(pages))
    page["lastmod"] = from_utc_format(pages[page_id]['revisions'][0]['timestamp'])
    page["link"] = f"{ARCHIVE_BASE}/wiki/{page_title}"
    doc_url = mw_page_doc_url(page)
    page["doc_link"] = doc_url if doc_url is not None else ""

    return page

# -------------------------------------------------------------------------------
# WikiSource HTML archive scraping


"""
# HTML page element processing
def form_element_text(element):
    text = element.text.strip() if element is not None else None
    return form_text_item(text)

def read_page(url):

    soup = BeautifulSoup(fetch_url(url), 'lxml')
    title = soup.find('span', attrs = {'class': 'mw-page-title-main'})
    desc = soup.find('span', attrs = {'id': 'header_section_text'})
    table = soup.find('table', attrs = {'class': 'wikitable'})
    children = []
    header = []
    if table:
        for tr_elem in table.find_all('tr'):
            if not header:
                for th_elem in tr_elem.find_all('th'):
                    header.append(form_element_text(th_elem))
            item = []
            for td_elem in tr_elem.find_all('td'):
                a_elem = td_elem.find('a')
                child_url = a_elem.get('href') if a_elem else None
                text = form_text_item(td_elem.text.strip())
                item.append({'text': text, 'link': child_url})
            if item:
                children.append(item)

    # check for document thumbnail
    doc_info = soup.find('figure', attrs = {'typeof': 'mw:File/Thumb'})
    doc_url = None
    thumb_url = None
    if doc_info:
        a_tag = doc_info.find('a')
        doc_url = a_tag.get('href')
        thumb_elem = a_tag.find('img')
        thumb_url = thumb_elem.get('src') if thumb_elem else None
    footer = soup.find('li', attrs={'id': 'footer-info-lastmod'})
    last_modified = lastmod(footer.text) if footer else None

    return {
        'title': form_element_text(title),
        'description': form_element_text(desc),
        'header': header,
        'children': children,
        'lastmod': last_modified,
        'link': url,
        'doc_link': doc_url,
        #'thumb_link': thumb_url,
    }
"""

# -------------------------------------------------------------------------------
# WikiSource change detection

def do_search(query_string, limit=10, offset=0):
    """
    Search archive site for matching entries, sorted on last modification date.
    For each hit, return dict with item with keys: title, link, and lastmod.
    """
    _logger.info(f'do_search({query_string}, limit={limit}, offset={offset})')
    query_string = quote(query_string, safe='', encoding=None, errors=None)
    url = f'{ARCHIVE_BASE}/w/index.php?limit={limit}&offset={offset}'
    url += f'&ns0=1&sort=last_edit_desc&search={query_string}'
    #_logger.info(f'search url={url}')
    soup = BeautifulSoup(fetch_url(url), 'lxml')
    results = []
    for result in soup.find_all('li', attrs = {'class': 'mw-search-result'}):
        div = result.find('div', attrs = {'class': 'mw-search-result-heading'})
        data = result.find('div', attrs = {'class': 'mw-search-result-data'})
        data = data.text.strip()
        pos = data.find('-')
        data = format_date(data[(pos + 1):].strip())
        item = {
            'title': div.a['title'],
            'link': div.a['href'],
            'lastmod': data
        }
        results.append(item)
    return results

def report_page_changes(page):
    """
    Print a report of changes detected in check_page_changes().
    """
    if not isinstance(page, dict):
        page = page.page
    if 'refmod' not in page:
        _logger.info(f"No changes to report. Run check_page_changes first.")
        return
    _logger.info(
        f'Change report for {get_text(page["title"])},' +
        f' lastmod={page["lastmod"]}, refmod={page["refmod"]}')
    for key in ['title', 'description']:
        if page[key]['edit'] is not None:
            _logger.info(f'{key}: {page[key]["edit"]}')
    for child in page['children']:
        index = get_text(child[0]['text'])
        for i, item in enumerate(child):
            if 'edit' in item and item['edit'] is not None:
                _logger.info(f'{index}[{i}] ({item["edit"]}): {get_text(item["text"])}')
            if 'link_edit' in item and item['link_edit'] is not None:
                _logger.info(f'{index}[{i}] (link {item["link_edit"]}): {item["link"]}')

def check_page_changes(page, reference, report=False):
    """
    Compare a given page to a prior version of the same page and return any detected changes.
    """
    if not isinstance(page, dict):
        page = page.page
    if not isinstance(reference, dict):
        reference = reference.page
    page['refmod'] = reference['lastmod']
    for key in ['title', 'description']:
        changed = not equal_text(page[key], reference[key])
        page[key]['edit'] = 'changed' if changed else None
    if 'doc_link' in page:
        if 'doc_link' in reference:
            if page['doc_link'] != reference['doc_link']:
                page['doc_link_edit'] = 'changed'
        else:
                page['doc_link_edit'] = 'added'

    ref_children = dict((get_text(c[0]['text']), c) for c in reference['children'])
    for child in page['children']:
        #print("checking child:", child)
        index = get_text(child[0]['text'])
        if index in ref_children:
            ref_child = ref_children[index]
            #print("comparing:", child, "to", ref_child)
            for item, ref_item in zip(child, ref_child):
                changed = not equal_text(item['text'], ref_item['text'])
                item['edit'] = 'changed' if changed else None
                if is_linked(item):
                    if is_linked(ref_item):
                        item['link_edit'] = 'changed' if item['link'] != ref_item['link'] else None
                    else:
                        item['link_edit'] = 'added'
        else:
            for item in child:
                item['edit'] = 'added'
    if report:
        report_page_changes(page)

def _page_update_summary(archive, change_list):
    #assert isinstance(archive, Archive)
    archive_prefix = archive.url[:archive.url.rfind('/')]
    archive_prefix = archive_prefix.replace(ARCHIVE_BASE, '')
    archive_prefix = archive_prefix.replace('%3A', ':')
    # Form list of fonds belonging to this archive
    fond_list={get_text(c[0]['text']) for c in archive.children}
    result = {}
    for item in change_list:
        page_spec = item["title"].split('/')
        address = (archive.tag, archive.subarchive["en"])
        address += tuple(entry for entry in page_spec[1:])
        address = (address + ("",) * 3)[:5]
        fond = address[2]
        address = ','.join(address)
        mod_date = item["lastmod"]
        # Confirm that the item belongs to the selected archive
        if fond in fond_list and item["link"].startswith(archive_prefix):
            if address in result:
                result[address] = max(mod_date, result["address"])
            else:
                result[address] = mod_date
    return result

def check_page_updates(archive, cutoff_date):
    #assert isinstance(archive, Archive)
    change_list = []
    batch_size = 50
    offset = 0
    while True:
        _logger.info(f'check_page_updates: {archive.name}, {batch_size}, {offset}')
        changes = archive.latest_changes(limit=batch_size, offset=offset)
        change_list += changes
        if not changes or changes[-1]["lastmod"] < cutoff_date:
            break
        offset += batch_size
        batch_size *= 2 # search geometrically longer history
    change_list = [item for item in change_list if item["lastmod"] >= cutoff_date]
    _logger.info(f"check_page_updates, {len(change_list)}, changes found")
    return _page_update_summary(archive, change_list)

# -------------------------------------------------------------------------------
# Get most recent page modification dates within given namespace

def get_recent_changes(namespace=WIKI_NAMESPACE_ID, cutoff_date=None, limit=500, sleep_time=0.1):
    """
    Collects the latest modification timestamp for each page in a given namespace,
    going back to the specified cutoff date.
    
    Args:
        namespace (int): Namespace number (e.g. 0 = main, 6 = file, etc.)
        cutoff_date (str): timestamp
        limit (int): Max results per request (max is 500 for users, 5000 for bots)
        sleep_time (float): Seconds to sleep between requests to avoid throttling

    Returns:
        dict: Mapping from page title to latest modification timestamp (ISO8601)
    """
    if not cutoff_date:
        cutoff_date = "2025"

    latest_mods = {}
    params = {
        "action": "query",
        "format": "json",
        "list": "recentchanges",
        "rcnamespace": namespace,
        "rcprop": "title|timestamp",
        "rclimit": limit,
        "rcend": to_utc_format(cutoff_date),
        "rcdir": "older",  # go backward in time
        "rcshow": "!redirect",
    }

    seen_pages = set()
    cont = {}

    while True:
        if cont:
            params.update(cont)
        data = fetch_url(API_URL, params=params, json=True)
        for rc in data.get("query", {}).get("recentchanges", []):
            title = rc["title"]
            timestamp = rc["timestamp"]
            if title not in seen_pages:
                seen_pages.add(title)
                latest_mods[title] = from_utc_format(timestamp)

        if "continue" in data:
            cont = data["continue"]
            time.sleep(sleep_time)
        else:
            break

    return latest_mods

# -------------------------------------------------------------------------------
# Get most recent page modification dates within given namespace

def get_last_mod(titles):
    """
    Return a dict of {page_title: last_modified_datetime} using fast batched 'prop=info' queries.
    Input: str or list of str (page titles)
    Output: dict {title: datetime or None}
    """
    if isinstance(titles, str):
        titles = [titles]

    result = {}
    for i in range(0, len(titles), 50):
        batch = titles[i:i+50]
        title_str = "|".join(batch)

        params = {
            "action": "query",
            "format": "json",
            "prop": "info",
            "titles": title_str,
        }

        response = fetch_url(API_URL, params=params, json=True)
        pages = response.get("query", {}).get("pages", {})

        for page in pages.values():
            title = page.get("title")
            touched = page.get("touched")
            result[title] = from_utc_format(touched) if touched else None

        # Fill in None for missing titles (e.g., typos or deleted pages)
        for title in batch:
            result.setdefault(title, None)

        #if i < len(titles):
        #    time.sleep(5)

    return result

# -------------------------------------------------------------------------------
# Keep persistable list of latest mod date per page title

class PageTracker:
    def __init__(self, mod_dates={}, cutoff_date=None):
        self._mod_dates = mod_dates
        self._cutoff_date = cutoff_date

    def to_dict(self):
        return {
            'mod_dates':        self._mod_dates,
            'cutoff_date':      self._cutoff_date,
        }

    @classmethod
    def from_dict(cls, d):
        return cls(
            mod_dates=d['mod_dates'],
            cutoff_date=d['cutoff_date'],
            )

    def least_recent(self):
        return min(self._mod_dates.items(), key=lambda x: x[1])

    def most_recent(self):
        return max(self._mod_dates.items(), key=lambda x: x[1])

    def update(self):
        updates = get_recent_changes(cutoff_date=self._cutoff_date)
        self._cutoff_date = max(updates.items(), key=lambda x: x[1])[1]
        any_change = False
        for page, mod_date in updates.items():
            if mod_date != self._mod_dates.get(page):
                any_change = True
                self._mod_dates[page] = mod_date
        return any_change

    def add_titles(self, titles):
        new_titles = [title for title in titles if title not in self._mod_dates]
        if not new_titles:
            return False

        updates = get_last_mod(new_titles)
        _logger.info(f'add_titles: found {len(updates)} updates')
        any_change = False
        for page, mod_date in updates.items():
            if mod_date != self._mod_dates.get(page):
                any_change = True
                self._mod_dates[page] = mod_date
        return any_change

    def get_updates(self, prefix, cutoff_date=None):
        prefix = prefix.replace("_", " ")
        if not prefix.startswith(WIKI_NAMESPACE):
            prefix = f"{WIKI_NAMESPACE}:{prefix}"
        def selected(title, mod_date):
            return title.startswith(prefix) and (not cutoff_date or mod_date >= cutoff_date)
        result = { title: mod_date for title, mod_date in self._mod_dates.items() if selected(title, mod_date)}
        return result

    def __getitem__(self, key):
        return self._mod_dates[key]

    def __contains__(self, key):
        return key in self._mod_dates

# -------------------------------------------------------------------------------
# Page revision history handling (using wiki API)

def wiki_title(page_title):
    return f'{WIKI_NAMESPACE}:{page_title}'

def history_url(page_title, limit=1):
    return ('https://uk.wikisource.org/w/api.php?action=query&format=json'
            '&prop=revisions&rvprop=ids|timestamp'
            f'&rvlimit={limit}&titles={quote(wiki_title(page_title))}')

def page_revision_url(page_title, revid):
    return ('https://uk.wikisource.org/w/index.php?'
            f'title={quote(wiki_title(page_title))}&oldid={revid}')

def get_page_history(page_title, limit=10):
    result = fetch_url(history_url(page_title, limit=limit), json=True)
    query = result.get('query')
    #_logger.info(f'get_page_history({page_title}, limit={limit}): result={query}')

    if not query:
        _logger.error(f'get_page_history({page_title}, limit={limit}): no result returned')
        return []
    pages = query.get('pages')
    if not pages:
        _logger.error(f'get_page_history({page_title}, limit={limit}): empty result returned')
        return []
    if '-1' in pages:
        _logger.error(f'get_page_history({page_title}, limit={limit}): unrecognized page name')
        return []
    # assume only one page is returned (in future, pass multiple to reduce api calls)
    for page in pages.values():
        history = [ {
            'revid': rev['revid'],
            'modified': from_utc_format(rev['timestamp']),
            'link': page_revision_url(page_title, rev['revid'])
        } for rev in page.get('revisions') ]
        return history
    _logger.error(f'get_page_history({page_title}, limit={limit}): unexpected result returned')
    return []

def get_page_history_from_cutoff(page_title, cutoff_date):
    # search increasingly for cutoff date  because
    # api does not allow for paging through search results
    last_result_length = 0
    attempt = 50
    while True:
        result = get_page_history(page_title, limit=attempt)
        if not result:
            _logger.error(f'get_page_history({page_title}, cutoff_date={cutoff_date}): empty history')
            return []
        if len(result) == last_result_length:
            result[-1]['created'] = True
            return result # no more history to be had
        if result[-1]['modified'] <= cutoff_date:
            for index, item in enumerate(result):
                if item['modified'] <= cutoff_date:
                    return result[:(index+1)]
            return result
        # increase limit length and try again
        last_result_length = len(result)
        attempt *= 2


# -------------------------------------------------------------------------------
# History LRU

class HistoryLRU:
    def __init__(self, maxsize=500, reset_limit=60 * 60):
        self._reset_limit = reset_limit  # seconds
        self._timer_start = time.time()
        self._lru = LRUCache(maxsize=maxsize)

    def _flush_if_needed(self):
        if time.time() - self._timer_start >= self._reset_limit:
            #_logger.info("HistoryLRU: flushing all entries")
            self._lru.clear()
            self._timer_start = time.time()

    def _filter_with_fallback(self, history, cutoff_date):
        split = next((i for i, h in enumerate(history) if h['modified'] <= cutoff_date), len(history))
        return history[:split + 1]

    def lookup(self, page_title, limit=10):
        self._flush_if_needed()
        try:
            history = self._lru[page_title]
            #_logger.info(f"HistoryLRU.lookup({page_title}): cache hit")
            if len(history) >= limit:
                return history[:limit]
            #_logger.info(f"HistoryLRU.lookup({page_title}): cache too short, refreshing")
        except KeyError:
            pass
            #_logger.info(f"HistoryLRU.lookup({page_title}): cache miss")
        # Refresh
        history = get_page_history(page_title, limit=limit)
        self._lru[page_title] = history
        return history[:limit]

    def lookup_by_cutoff(self, page_title, cutoff_date):
        self._flush_if_needed()
        try:
            history = self._lru[page_title]
            #_logger.info(f"HistoryLRU.lookup_by_cutoff({page_title}): cache hit")

            if history:
                oldest = history[-1]
                if oldest.get('created') or oldest['modified'] < cutoff_date:
                    # We have enough
                    return self._filter_with_fallback(history, cutoff_date)
                #_logger.info(f"HistoryLRU.lookup_by_cutoff({page_title}): cache incomplete, refreshing")
        except KeyError:
            pass
            #_logger.info(f"HistoryLRU.lookup_by_cutoff({page_title}): cache miss")

        # Refresh and filter
        history = get_page_history_from_cutoff(page_title, cutoff_date=cutoff_date)
        self._lru[page_title] = history
        return self._filter_with_fallback(history, cutoff_date)

# -------------------------------------------------------------------------------
# Document link extraction from wikitext

def _wiki_content_url(titles):
    batch_titles = '|'.join([quote(f'{WIKI_NAMESPACE}:{t}') for t in titles])
    return (f'{ARCHIVE_BASE}/w/api.php?'
            'action=query&format=json&prop=revisions&'
            'rvprop=content&rvslots=main&'
            f'titles={batch_titles}'
           )

def _extract_file_links(wikitext):
    wikicode = mwparserfromhell.parse(wikitext)
    file_links = []

    # 1. [[File:...]] wikilinks
    for link in wikicode.filter_wikilinks():
        title = str(link.title)
        if title.lower().startswith("file:"):
            file_links.append(title)

    # 2. Template param values
    for template in wikicode.filter_templates():
        for param in template.params:
            value_str = str(param.value)

            # (a) Extract wikilinks inside param value
            parsed_value = mwparserfromhell.parse(value_str)
            for link in parsed_value.filter_wikilinks():
                title = str(link.title)
                if title.lower().startswith("file:"):
                    file_links.append(title)

            # (b) Extract raw "File:..." patterns not wrapped in [[ ]]
            # Acceptable file name chars: letters, digits, spaces, punctuation
            raw_file_match = re.findall(r'\bFile:[^\|\}\n\r]+', value_str)
            file_links.extend(raw_file_match)

            # (c) Extract full file URLs (just in case)
            file_url_matches = re.findall(r'https?://uk\.wikisource\.org/wiki/File:([^\s|}]+)', value_str)
            for match in file_url_matches:
                file_links.append(f'File:{match.replace("_", " ")}')  # decode _

    return file_links

def _normalize_mediawiki_title(title):
    title = title.replace(' ', '_')         # Normalize space to underscore
    return title

def _file_link_to_url(link):
    if link.lower().startswith("file:"):
        filename = _normalize_mediawiki_title(link[5:])
        return f"/wiki/File:{filename}"
    else:
        return None

def _deduplicate_links(links):
    return list(dict.fromkeys(links))

def _chunked(iterable, size):
    """Yield successive chunks from iterable."""
    it = iter(iterable)
    while True:
        chunk = list(islice(it, size))
        if not chunk:
            break
        yield chunk

def batch_fetch_document_links(titles, map_to_url=True, chunk_size=20):
    if not isinstance(titles, (list, tuple)):
        titles = [titles]

    result = {}

    for chunk in _chunked(titles, chunk_size):
        data = fetch_url(_wiki_content_url(chunk), json=True)
        if not 'query' in data:
            _logger.error(f'batch_fetch_document_links returned:\n    {data}')
        for page in data['query']['pages'].values():
            title = page['title'].split(':', 1)[-1]  # strip 'Архів:' prefix
            try:
                wikitext = page['revisions'][0]['slots']['main']['*']
                links = _extract_file_links(wikitext)
                if map_to_url:
                    links = [_file_link_to_url(link) for link in links]
                result[title] = _deduplicate_links(links)
            except (KeyError, IndexError):
                result[title] = []

    return result
