#!/bin/bash
# (c) 2025 Jonathan Brandt
# Licensed under the MIT License. See LICENSE file in the project root.

export BIRDDOG_USE_LOCAL_CACHE=True
#export BIRDDOG_TRANSLATION_DEBUG=True
PORT=2003

echo "!!! STARTING BIRDDOG IN DEBUG MODE !!!"
echo "Starting Flask service on port $PORT..."
(sleep 5; open "http://127.0.0.1:$PORT") &
python3 -m birddog.service --port "$PORT" --debug
